### ISSUE TITLE
can't find apiGoogleconfig.json in ubuntu server

### ISSUE THREAD

**Issue by starcraft0429** [Insomniiak/react-google-calendar-api#11]
```
ERROR` in ../~/react-google-calendar-api/build/ApiCalendar.js
Module not found: Error: Can't resolve '../../apiGoogleconfig.json' in '/var/www/staging/development/source/node_modules/react-google-calendar-api/build'
 @ ../~/react-google-calendar-api/build/ApiCalendar.js 11:13-50
 @ ./src/components/Nanny/NannyProfile.js
 @ ./src/routes/index.js
 @ ./src/index.js
```

It think, it will be better if we set config by importing.
Automated resolving config might be problem.

I found some issue...
In my local windows machine, your package didn't build and run directly.
Btw in the ubuntu server node_modules/react-google-calendar-api/ I found ./build directory, so that your built package didn't know config json file path since directory level is changed.

Thanks in advance

**Comment by Insomniiak** [comment]
Hi, Yeah I see
Hmm maybe I should do an automated resolution Path because now this is hard coded in the import with "../../apiGoogleconfig.json"
Didn't thought about build configuration, I will change the hard coded Path, with "../../../apiGoogleconfig.json" temporary. And when I will find the time will do an automated Pathfinding

But if you want to contribute and do this you are welcome.
Thanks

**Comment by Insomniiak** [comment]
@starcraft0429 I fixed it temporary and tested it, now you can use it on your server.
I'm closing the issue if you have other problems or if this isn't working I'm here.

**Comment by starcraft0429** [comment]
Thanks @Insomniiak
